// Minimal provider – Icon map (Blueprint icon names → Lucide React components)
import {
   AlertCircle,
   AlertTriangle,
   AppWindow,
   ArrowLeft,
   ArrowRight,
   Ban,
   Check,
   ChevronDown,
   ChevronRight,
   ChevronUp,
   ChevronsUpDown,
   CircleArrowUp,
   Folder,
   Hand,
   Home,
   Image,
   Info,
   Layers,
   Layers2,
   LayersPlus,
   ListChecks,
   List,
   Map,
   MapPinSearch,
   Menu,
   MessageSquareMore,
   Minus,
   MousePointer,
   PanelLeftClose,
   PanelLeftOpen,
   Pencil,
   Play,
   Printer,
   Plus,
   Route,
   ScanSearch,
   Scaling,
   Search,
   Settings,
   Square,
   Tag,
   Table,
   Trash2,
   X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * @hidden
 * @since 0.15
 */
export const ICON_MAP: Record<string, LucideIcon | null> = {
   "arrow-left": ArrowLeft,
   "arrow-right": ArrowRight,
   "arrows-horizontal": Scaling,
   "application": AppWindow,
   "caret-down": ChevronDown,
   "caret-up": ChevronUp,
   "chevron-down": ChevronDown,
   "chevron-right": ChevronRight,
   "chevron-up": ChevronUp,
   "cog": Settings,
   "comment": MessageSquareMore,
   "cross": X,
   "delete": Trash2,
   "disable": Ban,
   "double-caret-vertical": ChevronsUpDown,
   "edit": Pencil,
   "error": AlertCircle,
   "folder-close": Folder,
   "geosearch": MapPinSearch,
   "hand": Hand,
   "home": Home,
   "info-sign": Info,
   "issue": AlertTriangle,
   "layer": Layers2,
   "layers": Layers,
   "map": Map,
   "media": Image,
   "menu-closed": PanelLeftClose,
   "menu-open": PanelLeftOpen,
   "minus": Minus,
   "multi-select": ListChecks,
   "new-layer": LayersPlus,
   "path-search": Route,
   "play": Play,
   "plus": Plus,
   "print": Printer,
   "properties": List,
   "search": Search,
   "select": MousePointer,
   "small-cross": X,
   "stop": Square,
   "tag": Tag,
   "th": Table,
   "tick": Check,
   "trash": Trash2,
   "upload": CircleArrowUp,
   "warning-sign": AlertTriangle,
   "zoom-to-fit": ScanSearch,
};

/**
 * @hidden
 * @since 0.15
 */
export function getIconComponent(name: string): LucideIcon | null {
   return ICON_MAP[name] ?? null;
}
