var STRINGS_DE = {
    "TPL_SIDEBAR_TITLE_TASKPANE": "Aufgabenbereich",
    "TPL_SIDEBAR_TITLE_LEGEND": "Legende",
    "TPL_SIDEBAR_TITLE_SELECTION_PANEL": "Auswahljury",
    "TPL_SIDEBAR_OPEN_TASKPANE": "Öffnen Sie den Task Pane",
    "TPL_SIDEBAR_OPEN_LEGEND": "Öffnen Legend",
    "TPL_SIDEBAR_OPEN_SELECTION_PANEL": "Öffnen Auswahljury",
    "TT_GO_HOME": "Nach Hause gehen",
    "TT_GO_BACK": "Geh zurück",
    "TT_GO_FORWARD": "Vorwärts gehen",
    "SESSION_EXPIRED": "Sitzung abgelaufen",
    "SESSION_EXPIRED_DETAILED": "Ihre aktuellen MapGuide Sitzung ist abgelaufen",
    "SESSION_EXPIRED_AVAILABLE_ACTIONS": "Mögliche Aktionen:",
    "SESSION_EXPIRED_RELOAD_VIEWER": "Neu laden den Betrachter",
    "ERR_UNREGISTERED_LAYOUT": "Fehler: Keine Namen Layout ({layout}) registriert",
    "ERR_UNREGISTERED_COMPONENT": "ERROR: No such registrierten Komponente ({componentId}). Sicherstellen, dass die Komponente wurde in der Komponentenregister mit der ID registriert: {componentId}",
    "LOADING_MSG": "Laden ...",
    "MENU_TASKS": "Aufgaben",
    "NO_SELECTED_FEATURES": "Keine ausgewählten Funktionen",
    "FMT_SCALE_DISPLAY": "Scale - 1:{scale}",
    "FMT_SELECTION_COUNT": "Ausgewählte {total} Funktionen in {layerCount} Schichten",
    "DIGITIZE_POINT_PROMPT": "Klicken Sie hier um zu beenden und einen Punkt an diesem Ort ziehen<br/><br/>Drücken Sie ESC abbrechen",
    "DIGITIZE_LINE_PROMPT": "Klicken Sie auf diese Position als Start einzustellen.<br/>Klicken Sie erneut auf die Linie zu beenden an dieser Position<br/><br/>Drücken Sie ESC abbrechen",
    "DIGITIZE_LINESTRING_PROMPT": "Klicken Sie auf diese Position als Start einzustellen.<br/>Klicken Sie erneut auf einen Scheitelpunkt an dieser Stelle hinzuzufügen.<br/>Halten Sie SHIFT und ziehen während der Digitalisierung in Freihandmodus zu zeichnen<br/></br>Double click to finish<br/>Drücken Sie ESC abbrechen",
    "DIGITIZE_CIRCLE_PROMPT": "Klicken Sie auf diese Position als das Zentrum zu setzen.<br/>Bewegen Sie auf den gewünschten Radius aus und klicken Sie erneut zu beenden<br/><br/>Drücken Sie ESC abbrechen",
    "DIGITIZE_RECT_PROMPT": "Klicken Sie auf diese Position als eine Ecke zu setzen.<br/>Klicken Sie erneut zu beenden, und setzen Sie diese Position als die andere Ecke<br/><br/>Drücken Sie ESC abbrechen",
    "DIGITIZE_POLYGON_PROMPT": "Klicken Sie auf diese Position als Start einzustellen.<br/>Klicken Sie erneut auf einen Scheitelpunkt an dieser Stelle hinzuzufügen.<br/>Halten Sie SHIFT und ziehen während der Digitalisierung in Freihandmodus zu zeichnen<br/><br/>Double click to finish and close the polygon<br/>Drücken Sie ESC abbrechen",
    "MEASURE": "Messen",
    "MEASUREMENT_TYPE": "Messart",
    "MEASUREMENT_TYPE_LENGTH": "Länge (Linestring )",
    "MEASUREMENT_TYPE_AREA": "Fläche (Polygon)",
    "MEASUREMENT_USE_GEODESIC": "Verwenden Sie geodätischen Mess",
    "MEASUREMENT_CLEAR": "klar Messungen",
    "MEASUREMENT_CONTINUE_POLYGON": "Klicken Sie, um weiterhin ein Polygon zeichnen. Doppelklicken Sie auf zu beenden.",
    "MEASUREMENT_CONTINUE_LINE": "Klicken Sie, um auch weiterhin die Linie zu zeichnen. Doppelklicken Sie auf zu beenden.",
    "MEASUREMENT_START_DRAWING": "Klicken Sie auf Zeichnung zu starten",
    "NAVIGATOR_PAN_EAST": "Pan East",
    "NAVIGATOR_PAN_WEST": "Pan Westen",
    "NAVIGATOR_PAN_SOUTH": "Pan Süd",
    "NAVIGATOR_PAN_NORTH": "Pan Nord",
    "NAVIGATOR_ZOOM_OUT": "Rauszoomen",
    "NAVIGATOR_ZOOM_IN": "Hineinzoomen",
    "FMT_NAVIGATOR_ZOOM_TO_SCALE": "Zoom bis 1:{scale}",
    "EXTERNAL_BASE_LAYERS": "Externe Base Layers",
    "SELECTION_PROPERTY": "Eigentum",
    "SELECTION_VALUE": "Wert",
    "SELECTION_PREV_FEATURE": "Zurück Eigenschaft",
    "SELECTION_NEXT_FEATURE": "Nächste Funktion",
    "SELECTION_ZOOMTO_FEATURE": "Zoom auf ausgewählte Funktion",
    "VIEWER_OPTIONS": "Viewer-Optionen",
    "ABOUT": "Etwa",
    "HELP": "Hilfe",
    "QUICKPLOT_HEADER": "Schnell-Plot",
    "QUICKPLOT_TITLE": "Titel",
    "QUICKPLOT_SUBTITLE": "Untertitel",
    "QUICKPLOT_PAPER_SIZE": "Papier größe",
    "QUICKPLOT_ORIENTATION": "Orientierung",
    "QUICKPLOT_ORIENTATION_P": "Porträt",
    "QUICKPLOT_ORIENTATION_L": "Landschaft",
    "QUICKPLOT_SHOWELEMENTS": "Elemente zeigen",
    "QUICKPLOT_SHOWLEGEND": "Legende anzeigen",
    "QUICKPLOT_SHOWNORTHARROW": "Zeige Nordpfeil",
    "QUICKPLOT_SHOWCOORDINTES": "Zeige Koordinaten",
    "QUICKPLOT_SHOWSCALEBAR": "Skala anzeigen Bar",
    "QUICKPLOT_SHOWDISCLAIMER": "anzeigen Haftungsausschluss",
    "QUICKPLOT_ADVANCED_OPTIONS": "Erweiterte Optionen",
    "QUICKPLOT_SCALING": "Skala",
    "QUICKPLOT_DPI": "DPI",
    "QUICKPLOT_GENERATE": "generieren Grundstück",
    "QUICKPLOT_COMMERCIAL_LAYER_WARNING": "Schnell-Plot wird keine sichtbaren kommerzielle Kartenschichten umfassen"
};