#!/usr/bin/env node
/**
 * snapshot-api.js
 *
 * Generates a deterministic, sorted manifest of the public API surface of the
 * `mapguide-react-layout` npm module, as resolved from the public barrel
 * (`src/index.ts`, generated by `yarn run build:barrels`).
 *
 * Each line describes one exported symbol, with tab-separated fields:
 *
 *     <kind>\t<name>\t<signature>\t<origin>
 *
 * The manifest is intended to be committed to version control so that the API
 * surface of different branches/releases can be compared with a plain diff:
 *
 *     git diff release-0.13..release-0.14 -- test-data/api-surface.txt
 *
 * Design notes:
 *  - Signatures are derived from declaration source text rather than
 *    checker-printed types, so output is stable across TypeScript versions
 *    (important when comparing branches that pin different TS versions).
 *  - Implementation bodies are stripped from functions, classes and component
 *    arrow functions, so implementation-only changes do not show up as API
 *    changes.
 *  - Comments and long string literals (e.g. base64 data URIs) are elided to
 *    keep the manifest readable and to avoid diff noise.
 *
 * Usage:
 *   yarn run snapshot:api
 *   node tools/snapshot-api.js [tsconfig] [outFile]
 *
 * Backporting: this script only depends on the `typescript` package, which is a
 * devDependency of every branch. Copy this file into `tools/` on the older
 * branch, add the `snapshot:api` script to that branch's package.json, run it,
 * and commit the generated `test-data/api-surface.txt`.
 */
const fs = require("fs");
const path = require("path");
const ts = require("typescript");

const REPO_ROOT = path.resolve(__dirname, "..");
const ENTRY = path.join(REPO_ROOT, "src", "index.ts");

/** Elide string literals longer than this (base64 assets, embedded blobs, ...). */
const MAX_STRING_LENGTH = 60;

const COMMENT_KINDS = new Set([
    ts.SyntaxKind.SingleLineCommentTrivia,
    ts.SyntaxKind.MultiLineCommentTrivia,
    ts.SyntaxKind.ConflictMarkerTrivia,
]);

const configPath = path.resolve(REPO_ROOT, process.argv[2] || "tsconfig.npm.json");
const outPath = path.resolve(REPO_ROOT, process.argv[3] || "test-data/api-surface.txt");

if (!fs.existsSync(ENTRY)) {
    console.error(`Could not find public entrypoint: ${path.relative(REPO_ROOT, ENTRY)}`);
    console.error(`Run 'yarn run build:barrels' first to generate it.`);
    process.exit(1);
}

const configFile = ts.readConfigFile(configPath, ts.sys.readFile);
if (configFile.error) {
    console.error(ts.flattenDiagnosticMessageText(configFile.error.messageText, "\n"));
    process.exit(1);
}

const parsed = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    path.dirname(configPath)
);

const program = ts.createProgram(parsed.fileNames, parsed.options);
const checker = program.getTypeChecker();

const resolvedEntry = ts.sys.resolvePath(ENTRY);
const entrySource = program
    .getSourceFiles()
    .find((sourceFile) => ts.sys.resolvePath(sourceFile.fileName) === resolvedEntry);

if (!entrySource) {
    console.error(`TypeScript did not include ${path.relative(REPO_ROOT, ENTRY)} in the program.`);
    process.exit(1);
}

const entrySymbol = checker.getSymbolAtLocation(entrySource);
if (!entrySymbol) {
    console.error(`Could not resolve a module symbol for ${path.relative(REPO_ROOT, ENTRY)}.`);
    process.exit(1);
}

const rows = checker.getExportsOfModule(entrySymbol).map(describeExport);

rows.sort((a, b) => a.name.localeCompare(b.name, "en") || a.kind.localeCompare(b.kind, "en"));

const lines = rows.map((row) => [row.kind, row.name, row.signature, row.origin].join("\t"));
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, lines.join("\n") + "\n");

console.log(`Wrote ${rows.length} exported symbols to ${path.relative(REPO_ROOT, outPath)}`);

/**
 * Builds the snapshot row for a single export of the public entrypoint.
 */
function describeExport(exported) {
    // The exported name is the name consumers import, which may differ from the
    // declaring name for renamed re-exports (`export { Foo as Bar }`).
    const name = exported.getName();
    const resolved = resolveAlias(exported);
    const declarations = [...(resolved.declarations || []), ...(exported.declarations || [])];

    // Ambient/shorthand modules (`declare module "*.png";`) and source files are
    // not useful declarations: asset re-exports resolve to them.
    const isOpaque = (node) =>
        ts.isSourceFile(node) || (ts.isModuleDeclaration(node) && !node.body);
    const declaration = declarations.find((node) => !isOpaque(node));
    const originDeclaration = declaration || declarations[0];

    if (!declaration) {
        // Nothing but opaque declarations available; treat as a module namespace.
        return {
            kind: "namespace",
            name,
            signature: `namespace ${name}`,
            origin: originOf(originDeclaration),
        };
    }

    // Asset/opaque re-export, e.g. `export { default as CURSOR_GRAB } from "...cur"`.
    if (ts.isExportSpecifier(declaration) || ts.isNamespaceExport(declaration)) {
        return {
            kind: "const",
            name,
            signature: `const ${name}`,
            origin: originOf(originDeclaration),
        };
    }

    return {
        kind: kindOf(resolved, declaration),
        name,
        signature: signatureOf(declaration, name),
        origin: originOf(declaration),
    };
}

/**
 * Follows re-export aliases (`export * from`, `export { x } from`) to the
 * symbol that actually declares the export.
 */
function resolveAlias(symbol) {
    let current = symbol;
    while (current.flags & ts.SymbolFlags.Alias) {
        current = checker.getAliasedSymbol(current);
    }
    return current;
}

function kindOf(symbol, declaration) {
    if (ts.isModuleDeclaration(declaration)) {
        return "namespace";
    }
    const flags = symbol.flags;
    if (flags & ts.SymbolFlags.Interface) return "interface";
    if (flags & ts.SymbolFlags.TypeAlias) return "type";
    if (flags & ts.SymbolFlags.Class) return "class";
    if (flags & ts.SymbolFlags.Enum) return "enum";
    if (flags & ts.SymbolFlags.Function) return "function";
    if (flags & ts.SymbolFlags.Variable) return "const";
    if (flags & ts.SymbolFlags.Module) return "namespace";
    return "unknown";
}

/**
 * Produces a single-line declaration signature.
 *
 *  - Functions/methods: declaration header only (body dropped).
 *  - Classes: declaration header only (members dropped).
 *  - Interfaces/type aliases/enums: full declaration, since the members *are*
 *    the public API.
 *  - Variables: declared type if present, otherwise the initializer with any
 *    embedded function bodies dropped (covers React components).
 */
function signatureOf(declaration, name) {
    const sourceFile = declaration.getSourceFile();

    if (ts.isVariableDeclaration(declaration)) {
        return variableSignature(declaration, name, sourceFile);
    }

    if (ts.isClassDeclaration(declaration) || ts.isClassExpression(declaration)) {
        return normalize(cutAtOpenBrace(declaration, sourceFile));
    }

    // Function-like declarations and namespace/module declarations expose a body.
    const body = declaration.body;
    if (body) {
        return normalize(textBefore(declaration, body, sourceFile));
    }

    return normalize(declaration.getText(sourceFile));
}

function variableSignature(declaration, name, sourceFile) {
    if (declaration.type) {
        return normalize(`const ${name}: ${declaration.type.getText(sourceFile)}`);
    }
    const initializer = declaration.initializer;
    if (!initializer) {
        return `const ${name}`;
    }
    return normalize(`const ${name} = ${initializerText(initializer, sourceFile)}`);
}

function initializerText(initializer, sourceFile) {
    if (ts.isArrowFunction(initializer) || ts.isFunctionExpression(initializer)) {
        return functionLikeText(initializer, sourceFile);
    }
    if (ts.isCallExpression(initializer)) {
        const callee = initializer.expression.getText(sourceFile);
        const typeArguments =
            initializer.typeArguments && initializer.typeArguments.length
                ? `<${initializer.typeArguments.map((arg) => arg.getText(sourceFile)).join(", ")}>`
                : "";
        const args = initializer.arguments.map((arg) =>
            ts.isArrowFunction(arg) || ts.isFunctionExpression(arg)
                ? functionLikeText(arg, sourceFile)
                : arg.getText(sourceFile)
        );
        return `${callee}${typeArguments}(${args.join(", ")})`;
    }
    return initializer.getText(sourceFile);
}

function functionLikeText(fn, sourceFile) {
    const params = fn.parameters.map((param) => param.getText(sourceFile)).join(", ");
    const returns = fn.type ? `: ${fn.type.getText(sourceFile)}` : "";
    return `(${params})${returns} => ...`;
}

function cutAtOpenBrace(node, sourceFile) {
    const brace = node
        .getChildren(sourceFile)
        .find((child) => child.kind === ts.SyntaxKind.OpenBraceToken);
    const end = brace ? brace.getStart(sourceFile) : node.getEnd();
    return node.getText(sourceFile).slice(0, end - node.getStart(sourceFile));
}

function textBefore(node, child, sourceFile) {
    return node
        .getText(sourceFile)
        .slice(0, child.getStart(sourceFile) - node.getStart(sourceFile));
}

/**
 * Collapses a declaration onto a single line, removing comments and eliding
 * long string literals. Edits are applied in place so the original spacing
 * between tokens is preserved (avoids introducing artefacts such as
 * `React.memo (...)`), which also keeps output stable across TypeScript
 * versions.
 */
function normalize(text) {
    const scanner = ts.createScanner(
        ts.ScriptTarget.Latest,
        /* skipTrivia */ false,
        ts.LanguageVariant.Standard,
        text
    );

    const edits = [];
    for (let token = scanner.scan(); token !== ts.SyntaxKind.EndOfFileToken; token = scanner.scan()) {
        const start = scanner.getTokenPos();
        const end = scanner.getTextPos();
        if (COMMENT_KINDS.has(token)) {
            edits.push({ start, end, replacement: " " });
        } else if (
            (token === ts.SyntaxKind.StringLiteral ||
                token === ts.SyntaxKind.NoSubstitutionTemplateLiteral) &&
            end - start > MAX_STRING_LENGTH
        ) {
            edits.push({ start, end, replacement: '"..."' });
        }
    }

    let result = "";
    let cursor = 0;
    for (const edit of edits) {
        result += text.slice(cursor, edit.start) + edit.replacement;
        cursor = edit.end;
    }
    result += text.slice(cursor);

    result = result.replace(/\s+/g, " ").trim();
    if (result.startsWith("export ")) {
        result = result.slice("export ".length);
    }
    if (result.endsWith("{")) {
        result = result.slice(0, -1).trim();
    }
    return result;
}

function originOf(declaration) {
    if (!declaration) {
        return "";
    }
    return path
        .relative(REPO_ROOT, declaration.getSourceFile().fileName)
        .split(path.sep)
        .join("/");
}
